# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc10dfb2208781044a14046545edfa26"
name = "Magic Sync Master"
handle = "magic-sync-master"
application_url = "https://c528-122-170-205-18.ngrok-free.app/"
embedded = true

[auth]
redirect_urls = [ "https://c528-122-170-205-18.ngrok-free.app/authenticate" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = true
